BOT_TOKEN = ""
ADMIN_ID = None
DB_FILE = "files/secret_santa.db"
WELCOME_MSG = "пиривет!"
PRINT_NAME_MSG = "Введи имя!"
PRINT_WISHES_MSG = "Введи предпочтения!"
SUCCESS_REGISTRY_MSG = "Вы зырегестрированы!"
YOU_BANED_MSG = "Вы заблокированы!"
YOU_KICKED_MSG = "Вы были выброшены из игры, но всё ещё можете повторно зарегестрироваться введя /start"
MENU_MSG = "Меню"
MSG_SEND = "Сообщение отправлено"
HAVE_NOT_PERMISSION = "Недостаточно доступа"
GAME_INFO = "Игра тайный друг, создана @mrgrantt"
open("files/admin.txt", "a+", encoding="utf-8")
with open("files/admin.txt", "r", encoding="utf-8") as f:
    value = f.read()
    if value and value != "":
        ADMIN_ID = int(value)